#!/bin/sh

PACKAGE_DIR="/var/packages/${SYNOPKG_PKGNAME}"
LOGFILE="${PACKAGE_DIR}/ulozto.log"
PIDFILE="${PACKAGE_DIR}/ulozto.pid"
TARGET_DIR="${PACKAGE_DIR}/target"
FILE_ENABLE="${PACKAGE_DIR}/enabled"

. /etc.defaults/rc.subr

ServiceStatus() {
	if [ -f "$PIDFILE" ]; then
		PID=$(cat "$PIDFILE")

		if [ -n "$(ps | grep -e $PID)" ]; then
			echo "${SYNOPKG_PKGNAME} service is running ..."
			return 1  # is running
		else
			echo "${SYNOPKG_PKGNAME} service is NOT running ..."
			rm -f ${PIDFILE}  # Remove Invalid PID
			return 0  # is NOT running
		fi
	else
		echo "${SYNOPKG_PKGNAME} service is NOT running ...."
		return 0  # is NOT running
	fi
}

StartService() {
	ServiceStatus
	if [ $? == 0 ]; then
		logger -t ${SYNOPKG_PKGNAME} -p warning "Service stoping"
		echo "Starting ${SYNOPKG_PKGNAME} service."
		cd ${TARGET_DIR} && nohup node server.js > ${LOGFILE} 2>&1&
		sleep 3
		#echo $! > "$PIDFILE"
		ps -e | grep 'Ulozto.cz' | awk '{print $1}' > ${PIDFILE}
  else
		echo "${SYNOPKG_PKGNAME} service already running."
  fi
}

StopService() {
	ServiceStatus
  if [ $? == 1 ]; then
		logger -t ${SYNOPKG_PKGNAME} -p warning "Service starting"
		echo "Stopping ${SYNOPKG_PKGNAME} service."
  	kill -15 $(cat "$PIDFILE") 1>&2> /dev/null ;
		echo "${SYNOPKG_PKGNAME} service stopped"
		rm -f "${LOGFILE}"
		sleep 1
	else
		echo "${SYNOPKG_PKGNAME} service could not be stopped"
	fi
}

case "$1" in
	start)
		StartService
		sleep 1
		ServiceStatus
		exit $(( ! $? ))  # [ $? == 1 ] && exit 0 || exit 1  # this if statement flips the boolean outcome.
		;;
	stop)
		StopService
		sleep 1
		ServiceStatus
		exit $?
		;;
	restart)
		StopService
		sleep 1
		StartService
		sleep 1
		ServiceStatus
		exit $(( ! $? ))  # this if statement flips the boolean outcome.
		;;
	status)
		ServiceStatus
		exit $(( ! $? ))  # this if statement flips the boolean outcome.
		;;
	log)
		echo "${LOGFILE}"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status|log}" >&2
		exit 1
		;;
esac

exit 0
